<!doctype html><html lang="zh-tw">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="此
文件已有 新
版本！
      
在Java中如果應用程式發生錯誤，會將錯誤相關資訊以例外物件包裝後再丟出，例外可能是由JVM產生，或者是你自行丟出，無論如何，以例外物件的形式，
給了...">

<meta property="og:locale" content="zh_TW">
<meta property="og:title" content="例外繼承架構">
<meta property="og:type" content="article">
<meta property="og:url" content="https://openhome.cc/Gossip/JavaEssence/ExceptionHierarchy.html">
<meta property="og:image" content="https://openhome.cc/Gossip/images/caterpillar_small.jpg">
<meta property="og:site_name" content="OPENHOME.CC">
<meta property="og:description" content="此
文件已有 新
版本！
      
在Java中如果應用程式發生錯誤，會將錯誤相關資訊以例外物件包裝後再丟出，例外可能是由JVM產生，或者是你自行丟出，無論如何，以例外物件的形式，
給了...">


    <title>例外繼承架構</title>

<link rel="stylesheet" href="../css/pure-0.6.0/pure-min.css">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="../css/layouts/side-menu-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="../css/layouts/side-menu.css">
    <!--<![endif]-->
  

     <link rel="stylesheet" href="../css/caterpillar.css">
     <script async src="../google-code-prettify/run_prettify.js"></script>
<!-- 網頁層級廣告 --><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle =window.adsbygoogle || []).push({google_ad_client: "ca-pub-9750319131714390",enable_page_level_ads: true });</script></head>
<body>

<div id="layout">
    <!-- Menu toggle -->
    <a href="ExceptionHierarchy.html#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon --><span></span>
        
    </a>
    <div id="menu">
        <div class="pure-menu">
            <a class="pure-menu-heading" href="index.html">回 Java Essence</a>
            <ul class="pure-menu-list">
                <br><div class="social" style="text-align: center;"><a href="http://twitter.com/caterpillar"><img title="Twitter" alt="Twitter" src="../images/twitter.png"></a> <a href="http://www.facebook.com/openhome.cc"><img title="Facebook" alt="Facebook" src="../images/facebook.png"></a> </div><br><div id="search box"><script>(function() {var cx = 'partner-pub-9750319131714390:3926766884';var gcse = document.createElement('script');gcse.type = 'text/javascript';gcse.async = true;gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.google.com/cse/cse.js?cx=' + cx;var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(gcse, s);})();</script><gcse:searchbox-only></gcse:searchbox-only></div><br><div class="ad" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 2015 新版型 160 x 600 廣告 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-9750319131714390"
     data-ad-slot="3747048883"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></li>
            </ul>
        </div>
    </div>

    <main id="main">
        <header class="header">
            <h1>例外繼承架構</h1>
        </header>

        <article class="content"><br><div class="ad-3" style="text-align: center;"><script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型回應式廣告 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="7104125683" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div> 
            此
文件已有 <a href="../Java/ThrowableHierarchy.html">新
版本</a>！<br>
      <br>
在Java中如果應用程式發生錯誤，會將錯誤相關資訊以例外物件包裝後再丟出，例外可能是由JVM產生，或者是你自行丟出，無論如何，以例外物件的形式，
給了你機會來面對與操作這個物件，也就是面對錯誤並進行改正的機會。<br>
      <br>
學習Java的人都知道的，例外處理的語法無非就是try..catch...finally，然而其實最重要的，並不在於語法，而在於例外的繼承架構：<br>
      
      <div style="margin-left: 40px;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace; color: red;">Throwable</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　<span style="color: red;">Error（嚴重的系統錯誤）</span></span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　LinkageError</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　ThreadDeath</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　VirtualMachineError</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　....</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　<span style="color: red;">Exception</span></span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　ClassNotFoundException<br>
      </span> <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　CloneNotSupportedException</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　IllegalAccessException<br>
      </span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　</span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">IOException<br>
      </span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　</span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　FileNotFoundException<br>
      <br>
      </span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;"></span>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　....</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　<span style="color: red;">RuntimeException（執行時期例外）</span></span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　　　ArithmeticException</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　　　ArrayStoreException</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　　　ClassCastException</span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">　
　　　　　....</span><br>
      </div>
      <br>
實際上所有錯誤發生時，包含錯誤資訊的物件，都是<span style="font-weight: bold;">一種（is a）</span>Throwable
的物件，Throwable定義了錯誤訊息的取得、堆疊追蹤（Stack Trace）等方法。在其下有兩個子類別：Error與Exception。<br>
      <br>
      Error的相關子類別代表嚴
重的系統錯誤，例如硬體錯誤、JVM錯誤或記憶體不足等問題，雖然基本上，也可以使用try...catch來處理Error物件，但並不建議，當發生嚴
重系統錯誤時，都是Java應用程式所無力回復的，舉個例子來說，如果JVM所需記憶體不足，你如何直接要求作業系統給予JVM更多記憶體呢？所以
Error物件丟出時，基本上不用處理，任由其傳播至JVM為止，或者是最多留下日誌（log）訊息。<br>
      <br>
      <span style="font-weight: bold;">如果一個Throwable物件沒有任何處理，最後傳播至JVM時，
JVM只有一種處理方式，顯示堆疊追蹤後直接中斷程式。</span><br>
      <br>
      <span style="font-weight: bold;">Exception下的子類別代表Java應用程式「可能」處理的狀
況，你可以使用try...catch語法嘗試將應用程式回復至可執行的狀態。</span><br>
      <br>
在Java程式碼中，如果某個操作會丟出Exception下的子物件，但非屬於RuntimeException的子物件，則你必須明確使用
try...catch語法加以處理，或者至少在方法用throws宣告這個方法會丟出例外，否則的話，編譯器不會讓程式
碼通過編譯，例如：<br>
      
      <div style="margin-left: 40px;">import
java.io.*;<br>
      public
class Main {<br>
      &nbsp;&nbsp;&nbsp;
public static void main(String[] args) {<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Reader reader = new FileReader(args[1]);<br>
      &nbsp;
&nbsp; &nbsp; &nbsp; ....<br>
      &nbsp;&nbsp;&nbsp;
}<br>
      }<br>
      </div>
      <br>
如果你直接編譯這個程式，則編譯器會出現以下的編譯錯誤訊息：<br>
      
      <div style="margin-left: 40px;"><span style="font-weight: bold;">Main.java:4: unreported exception
java.io.FileNotFoundException; must be caught or declared to be thrown</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Reader reader = new FileReader(args[1]);</span><br>
      </div>
      <br>
這是由於FileReader建構方法上，宣告會丟出FileNotFoundException：<br>
      
      <div style="margin-left: 40px;"><span style="font-weight: bold;">public FileReader(String fileName) throws
FileNotFoundException</span><br>
      </div>
      <br>
FileNotFoundException
是IOException的子類別，也就是Exception的子類別，編譯器發現你使用FileReader建構方法時，沒有明確使用try..
catch加以處理，也沒有使用throws在main上宣告丟出，因此不讓你通過編譯。如果想要通過編譯，一個方式是：<br>
      
      <div style="margin-left: 40px;"><span style="font-weight: bold;">import java.io.*;</span><br>
      <span style="font-weight: bold;">public class Main {</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public static void
main(String[] args) {</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
try {</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Reader reader = new FileReader(args[1]);</span><br>
      <span style="font-weight: bold;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
...</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
catch(FileNotFoundException ex) {</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
ex.printStackTrace();</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br>
      <span style="font-weight: bold;">&nbsp; &nbsp; &nbsp; &nbsp; ...</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br>
      <span style="font-weight: bold;">}</span><br>
      </div>
      <br>
另一個方法是：<br>
      
      <div style="margin-left: 40px;">import
java.io.*;<br>
      public
class Main {<br>
      &nbsp;&nbsp;&nbsp;
public static void main(String[] args) throws FileNotFoundException {<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Reader reader = new FileReader(args[1]);<br>
      &nbsp;
&nbsp; &nbsp; &nbsp; ....<br>
      &nbsp;&nbsp;&nbsp;
}<br>
      }<br>
      </div>
      <br>
採用哪個方式，完全看你的需求而定。像這種Exception下的子物件，但非屬於RuntimeException的子
物件，有個名稱叫作<span style="font-weight: bold;">受檢例外（Checked Exception）</span>，
受誰檢查？受編譯器檢查。受檢例外存在之目的，在於程式編寫者認定，你進行某個操作時，出錯的機會太高，因此要編譯器來協助（或提醒）你明確加以處理，你<span style="font-weight: bold;">無權選擇</span>要不要處理。<br>
      <br>
      屬
於RuntimeException衍生出來的類別，則是由JVM在執行時期會自動丟出的例外，情況通常是你事先無法預測錯誤是否會發生，例如透過參考至
null的變數來試圖操作，會丟出NullPointerExceptioon，或者是使用者輸
入是否正確，這種並不是事先可以得知使用者如何輸入的。例外時期例外，不需要特別使用try-catch或是在函式上使用throws宣告也
可以通過編譯，又稱為<span style="font-weight: bold;">非受檢例外（Unchecked Exception）</span>。
例如您在使用陣列時，並不一定要處理ArrayIndexOutOfBoundsException例外也可以通過編譯，你<span style="font-weight: bold;">有權選擇</span>要不要處理，或是丟出去給別的呼叫者，甚至最後傳播至JVM。<br>
      <br>
      瞭
解例外處理的繼承架構是必須的，除了解Error與Exception的區別，以及Exception、RuntimeException的分別之外，在
使用try..catch捕捉例外物件時，如果父類別例外物件撰寫在子類別例外物件之前被捕捉，則catch子類別例外物件的區塊將永遠不會被執行，事實
上編譯器也會幫您檢查這個錯誤。例如： <br>
      
      <div style="margin-left: 40px;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">import
java.io.*; </span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;"></span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">public
class Main { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
public static void main(String[] args) { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
try { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
throw new ArithmeticException("例外測試"); </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
catch(Exception e) { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
System.out.println(e.toString()); </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
catch(ArithmeticException e) { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
System.out.println(e.toString()); </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}
      </span><br>
      </div>
      <br>
      這個程式若在編譯時將會產生以下的錯誤訊息：<br>
      
      <div style="margin-left: 40px;"><span style="font-weight: bold;">Main.java:11: exception
java.lang.ArithmeticException has already been caught</span><br>
      <span style="font-weight: bold;">catch(ArithmeticException e) {</span><br>
      <span style="font-weight: bold;">^</span><br>
      </div>
      <br>
      要完成這個程式的編譯，你必須更改例外物件捕捉的順序，例如：<br>
      <div style="margin-left: 40px;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">import
java.io.*; </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">public
class Main { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
public static void main(String[] args) { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
try { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
throw new ArithmeticException("例外測試"); </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
catch(ArithmeticException e) { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
System.out.println(e.toString()); </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
catch(Exception e) { </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
System.out.println(e.toString()); </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
} </span><br>
      <span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}
      </span><br>
      </div>
      <br>
      在撰寫程式時，也可以如上將Exception例外物件的捕捉撰寫在最後，以便捕捉到所有尚未考慮到的例外，並進一步改進程
式。<br>
      

<br><br><div class="ad336-280" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型廣告 336 x 280 --><ins class="adsbygoogle" style="display:inline-block;width:336px;height:280px" data-ad-client="ca-pub-9750319131714390" data-ad-slot="9976409681"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div><br><div class="recommend" style="text-align: center;"><hr><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 自動大小回應相符內容 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="4953478487" data-ad-format="autorelaxed"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div></article></main></div></body>
<script src="../js/ui.js"></script>
</html>
<div class="analytics"><script async src="https://www.googletagmanager.com/gtag/js?id=G-QVQQYFSC8J"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-QVQQYFSC8J');</script></div>
