<!doctype html><html lang="zh-tw">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="在重重的方法呼叫下，例外發生的點可能是在某個方法之中，若想得知例外發生的根源，以及重重方法呼叫下傳播的呼叫堆疊，則可以利用例外物件所自動收集的堆疊追蹤（Stack Trace）來取得相關的資訊。最簡單...">

<meta property="og:locale" content="zh_TW">
<meta property="og:title" content="堆疊追蹤">
<meta property="og:type" content="article">
<meta property="og:url" content="https://openhome.cc/Gossip/JavaEssence/StackTrace.html">
<meta property="og:image" content="https://openhome.cc/Gossip/images/caterpillar_small.jpg">
<meta property="og:site_name" content="OPENHOME.CC">
<meta property="og:description" content="在重重的方法呼叫下，例外發生的點可能是在某個方法之中，若想得知例外發生的根源，以及重重方法呼叫下傳播的呼叫堆疊，則可以利用例外物件所自動收集的堆疊追蹤（Stack Trace）來取得相關的資訊。最簡單...">


    <title>堆疊追蹤</title>

<link rel="stylesheet" href="../css/pure-0.6.0/pure-min.css">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="../css/layouts/side-menu-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="../css/layouts/side-menu.css">
    <!--<![endif]-->
  

     <link rel="stylesheet" href="../css/caterpillar.css">
     <script async src="../google-code-prettify/run_prettify.js"></script>
<!-- 網頁層級廣告 --><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle =window.adsbygoogle || []).push({google_ad_client: "ca-pub-9750319131714390",enable_page_level_ads: true });</script></head>
<body>

<div id="layout">
    <!-- Menu toggle -->
    <a href="StackTrace.html#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon --><span></span>
        
    </a>
    <div id="menu">
        <div class="pure-menu">
            <a class="pure-menu-heading" href="index.html">回 Java Essence</a>
            <ul class="pure-menu-list">
                <br><div class="social" style="text-align: center;"><a href="http://twitter.com/caterpillar"><img title="Twitter" alt="Twitter" src="../images/twitter.png"></a> <a href="http://www.facebook.com/openhome.cc"><img title="Facebook" alt="Facebook" src="../images/facebook.png"></a> </div><br><div id="search box"><script>(function() {var cx = 'partner-pub-9750319131714390:3926766884';var gcse = document.createElement('script');gcse.type = 'text/javascript';gcse.async = true;gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.google.com/cse/cse.js?cx=' + cx;var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(gcse, s);})();</script><gcse:searchbox-only></gcse:searchbox-only></div><br><div class="ad" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 2015 新版型 160 x 600 廣告 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-9750319131714390"
     data-ad-slot="3747048883"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></li>
            </ul>
        </div>
    </div>

    <main id="main">
        <header class="header">
            <h1>堆疊追蹤</h1>
        </header>

        <article class="content"><br><div class="ad-3" style="text-align: center;"><script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型回應式廣告 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="7104125683" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div> 
            在重重的方法呼叫下，例外發生的點可能是在某個方法之中，若想得知例外發生的根源，以及重重方法呼叫下傳播的呼叫堆疊，則可以利用例外物件所自動收集的堆疊追蹤（Stack Trace）來取得相關的資訊。<br><br>最簡單的方法，就是直接呼叫例外物件的printStackTrace()來顯示堆疊追蹤。例如：<br><div style="margin-left: 40px;"><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">public class Main {&nbsp;&nbsp;&nbsp; </span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; public static String a() {</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String text = null;</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return text.toUpperCase();</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; }</span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;"></span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; public static void b() {</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a();</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; }</span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;"></span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; public static void c() {</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; b();</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; }</span><span style="font-weight: bold; font-family: Courier New,Courier,monospace;"></span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; public static void main(String[] args) {</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c();</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch(NullPointerException ex) {</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ex.printStackTrace();</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold; font-family: Courier New,Courier,monospace;">}</span><br></div><br>這個程式中，c()方法呼叫b()方法，b()方法呼叫a()方法，而a()方法中會引發NullPointerException，假設你並不知道這個呼叫的順序（也許你是在使用一個程式庫），當例外發生而被捕捉後，你可以呼叫<span style="font-weight: bold;">printStackTrace()</span>在主控台（Console）顯示堆疊追蹤：<br><div style="margin-left: 40px;"><span style="font-weight: bold;">java.lang.NullPointerException</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.a(Main.java:4)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.b(Main.java:8)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.c(Main.java:12)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.main(Main.java:17)</span><br></div><br>堆疊追蹤訊息中顯示了例外的類型，最頂層是例外的根源，以下是呼叫方法的順序，所顯示的程式碼行數，是對應於當初你的程式原始碼。printStackTrace()還有接受PrintStream、PrintWriter的版本，可以讓你將堆疊追蹤訊息以指定的IO輸出。<br><br>如果想要取得個別的堆疊追蹤元素進行處理，則可以使用<span style="font-weight: bold;">getStackTrace()</span>，這會傳回StackTraceElement陣列，陣列中索引0為例外根源的相關資訊，之後為各方法呼叫中的資訊，可以使用StackTraceElement的getClassName()、getFileName()、getLineNumber()、getMethodName()等方法取得對應的資訊。<br><br>&nbsp;要善用堆疊追蹤，前題是你不能在程式碼中有私吞例外的行為，例如在捕捉例外後什麼都不作：<br><div style="margin-left: 40px;"><span style="font-weight: bold;">try {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; ...</span><br><span style="font-weight: bold;">} catch(SomeException ex) {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; // 什麼也沒有</span><br><span style="font-weight: bold;">}</span><br></div><br>這樣的程式碼之所以會對應用程式造成嚴重的傷害，就在於例外訊息完全中止在這邊，之後呼叫此片段程式碼的客戶端，完全不知道發生了什麼事，在除錯時會異常困難，甚至找不出錯誤的根源，另一種就是對例外作了不適當的處理，或顯示了不正確的資訊，例如有些時候，由於某個例外階層下引發的例外類型很多，例如：<br><div style="margin-left: 40px;"><span style="font-weight: bold;">try {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; ...</span><br><span style="font-weight: bold;">} catch(FileNotFoundException ex) {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; // ...</span><span style="font-weight: bold;"></span><br><span style="font-weight: bold;"></span><span style="font-weight: bold;">} catch(EOFException ex) {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; // ...</span><br><span style="font-weight: bold;">}</span><br></div><span style="font-weight: bold;"><br></span>有些程式設計人員為了省麻煩，就會寫成這樣：<span style="font-weight: bold;"><br></span><div style="margin-left: 40px;"><span style="font-weight: bold;">try {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; ...</span><br><span style="font-weight: bold;">} catch(IOException ex) {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; ...</span><br><span style="font-weight: bold;">}</span><br></div><br>而後或許在找不到檔案時，覺得需要顯示些訊息：<br><div style="margin-left: 40px;"><span style="font-weight: bold;">try {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; ...</span><br><span style="font-weight: bold;">} catch(IOException ex) {</span><br><span style="font-weight: bold;">&nbsp; &nbsp; System.out.println("找不到檔案");</span><br><span style="font-weight: bold;">}</span><br><span style="font-weight: bold;"></span></div><span style="font-weight: bold;"><br></span>類似這樣的程式碼，在專案中履見不鮮，假以時日，或者是別人在除錯時，發現錯誤訊息是找不到檔案，<span style="font-weight: bold;">因而誤導了除錯的方向</span>，事實上可能其它原因<span style="font-family: Arial;">（IOException的其它子類型例外</span>）。<br><br>在使用<span style="font-family: Arial;">throw</span>重拋例外時，例外的追蹤堆疊起點，仍是例外的發生根源，而不是重拋例外的地方。例如：<br><div style="margin-left: 40px;">public class Main {&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; public static String a() {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String text = null;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return text.toUpperCase();<br>&nbsp;&nbsp;&nbsp; }&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; public static void b() {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a();<br>&nbsp;&nbsp;&nbsp; }&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; public static void c() {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; b();<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } catch(NullPointerException ex) {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ex.printStackTrace();<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.out.println("重拋例外");<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw ex;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; }&nbsp;&nbsp;&nbsp; <br>&nbsp;&nbsp;&nbsp; public static void main(String[] args) {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c();<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch(NullPointerException ex) {<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ex.printStackTrace();<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>&nbsp;&nbsp;&nbsp; }<br>}<br></div><br>執行這個程式，會發生以下的例外堆疊訊息：<br><div style="margin-left: 40px;">java.lang.NullPointerException<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.a(Main.java:4)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.b(Main.java:8)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.c(Main.java:13)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.main(Main.java:24)<br>重拋例外<br>java.lang.NullPointerException<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.a(Main.java:4)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.b(Main.java:8)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.c(Main.java:13)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.main(Main.java:24)<br></div><span style="font-weight: bold;"></span><br>如果你想要讓例外堆疊起點為重拋例外的地方，則可以使用<span style="font-weight: bold;">fillInStackTrace()</span>，這個方法會重新裝填例外堆疊，將起點設為重拋例外的地方，並傳回Throwable物件。例如：<br><div style="margin-left: 40px;"><span style="font-weight: bold;">public class Main {&nbsp;&nbsp;&nbsp; </span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public static String a() {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String text = null;</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return text.toUpperCase();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><span style="font-weight: bold;"></span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public static void b() {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><span style="font-weight: bold;"></span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public static void c() {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; b();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } catch(NullPointerException ex) {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ex.printStackTrace();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.out.println("重拋例外");</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw (NullPointerException) ex.fillInStackTrace();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><span style="font-weight: bold;"></span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public static void main(String[] args) {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch(NullPointerException ex) {</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ex.printStackTrace();</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br><span style="font-weight: bold;">}</span><br></div><br>執行這個程式，會發生以下的訊息：<br><div style="margin-left: 40px;"><span style="font-weight: bold;">java.lang.NullPointerException</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.a(Main.java:4)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.b(Main.java:8)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.c(Main.java:13)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.main(Main.java:24)</span><br><span style="font-weight: bold;">重拋例外</span><br><span style="font-weight: bold;">java.lang.NullPointerException</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.c(Main.java:17)</span><br><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; at Main.main(Main.java:24)</span><br></div><br>




<br><br><div class="ad336-280" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型廣告 336 x 280 --><ins class="adsbygoogle" style="display:inline-block;width:336px;height:280px" data-ad-client="ca-pub-9750319131714390" data-ad-slot="9976409681"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div><br><div class="recommend" style="text-align: center;"><hr><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 自動大小回應相符內容 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="4953478487" data-ad-format="autorelaxed"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div></article></main></div></body>
<script src="../js/ui.js"></script>
</html>
<div class="analytics"><script async src="https://www.googletagmanager.com/gtag/js?id=G-QVQQYFSC8J"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-QVQQYFSC8J');</script></div>
